//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7b.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telephone", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Telephone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        private int numberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Lab7b.ServiceReference.HelloWorldResponse HelloWorld(Lab7b.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.HelloWorldResponse> HelloWorldAsync(Lab7b.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        Lab7b.ServiceReference.GetAllResponse GetAll(Lab7b.ServiceReference.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.GetAllResponse> GetAllAsync(Lab7b.ServiceReference.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name GetDictResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        Lab7b.ServiceReference.GetDictResponse GetDict(Lab7b.ServiceReference.GetDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.GetDictResponse> GetDictAsync(Lab7b.ServiceReference.GetDictRequest request);
        
        // CODEGEN: Generating message contract since element name surname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        Lab7b.ServiceReference.AddDictResponse AddDict(Lab7b.ServiceReference.AddDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.AddDictResponse> AddDictAsync(Lab7b.ServiceReference.AddDictRequest request);
        
        // CODEGEN: Generating message contract since element name surname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        Lab7b.ServiceReference.UpdDictResponse UpdDict(Lab7b.ServiceReference.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.UpdDictResponse> UpdDictAsync(Lab7b.ServiceReference.UpdDictRequest request);
        
        // CODEGEN: Generating message contract since element name DelDictResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        Lab7b.ServiceReference.DelDictResponse DelDict(Lab7b.ServiceReference.DelDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.DelDictResponse> DelDictAsync(Lab7b.ServiceReference.DelDictRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Lab7b.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Lab7b.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(Lab7b.ServiceReference.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(Lab7b.ServiceReference.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(string GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.GetDictRequestBody Body;
        
        public GetDictRequest() {
        }
        
        public GetDictRequest(Lab7b.ServiceReference.GetDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictRequestBody {
        
        public GetDictRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.GetDictResponseBody Body;
        
        public GetDictResponse() {
        }
        
        public GetDictResponse(Lab7b.ServiceReference.GetDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7b.ServiceReference.Telephone[] GetDictResult;
        
        public GetDictResponseBody() {
        }
        
        public GetDictResponseBody(Lab7b.ServiceReference.Telephone[] GetDictResult) {
            this.GetDictResult = GetDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.AddDictRequestBody Body;
        
        public AddDictRequest() {
        }
        
        public AddDictRequest(Lab7b.ServiceReference.AddDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int number;
        
        public AddDictRequestBody() {
        }
        
        public AddDictRequestBody(string surname, int number) {
            this.surname = surname;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.AddDictResponseBody Body;
        
        public AddDictResponse() {
        }
        
        public AddDictResponse(Lab7b.ServiceReference.AddDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddDictResult;
        
        public AddDictResponseBody() {
        }
        
        public AddDictResponseBody(string AddDictResult) {
            this.AddDictResult = AddDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.UpdDictRequestBody Body;
        
        public UpdDictRequest() {
        }
        
        public UpdDictRequest(Lab7b.ServiceReference.UpdDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int number;
        
        public UpdDictRequestBody() {
        }
        
        public UpdDictRequestBody(int id, string surname, int number) {
            this.id = id;
            this.surname = surname;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.UpdDictResponseBody Body;
        
        public UpdDictResponse() {
        }
        
        public UpdDictResponse(Lab7b.ServiceReference.UpdDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdDictResult;
        
        public UpdDictResponseBody() {
        }
        
        public UpdDictResponseBody(string UpdDictResult) {
            this.UpdDictResult = UpdDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDict", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.DelDictRequestBody Body;
        
        public DelDictRequest() {
        }
        
        public DelDictRequest(Lab7b.ServiceReference.DelDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DelDictRequestBody() {
        }
        
        public DelDictRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDictResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab7b.ServiceReference.DelDictResponseBody Body;
        
        public DelDictResponse() {
        }
        
        public DelDictResponse(Lab7b.ServiceReference.DelDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DelDictResult;
        
        public DelDictResponseBody() {
        }
        
        public DelDictResponseBody(string DelDictResult) {
            this.DelDictResult = DelDictResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Lab7b.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Lab7b.ServiceReference.WebServiceSoap>, Lab7b.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.ServiceReference.HelloWorldResponse Lab7b.ServiceReference.WebServiceSoap.HelloWorld(Lab7b.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Lab7b.ServiceReference.HelloWorldRequest inValue = new Lab7b.ServiceReference.HelloWorldRequest();
            inValue.Body = new Lab7b.ServiceReference.HelloWorldRequestBody();
            Lab7b.ServiceReference.HelloWorldResponse retVal = ((Lab7b.ServiceReference.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.HelloWorldResponse> Lab7b.ServiceReference.WebServiceSoap.HelloWorldAsync(Lab7b.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            Lab7b.ServiceReference.HelloWorldRequest inValue = new Lab7b.ServiceReference.HelloWorldRequest();
            inValue.Body = new Lab7b.ServiceReference.HelloWorldRequestBody();
            return ((Lab7b.ServiceReference.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.ServiceReference.GetAllResponse Lab7b.ServiceReference.WebServiceSoap.GetAll(Lab7b.ServiceReference.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public string GetAll() {
            Lab7b.ServiceReference.GetAllRequest inValue = new Lab7b.ServiceReference.GetAllRequest();
            inValue.Body = new Lab7b.ServiceReference.GetAllRequestBody();
            Lab7b.ServiceReference.GetAllResponse retVal = ((Lab7b.ServiceReference.WebServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.GetAllResponse> Lab7b.ServiceReference.WebServiceSoap.GetAllAsync(Lab7b.ServiceReference.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.ServiceReference.GetAllResponse> GetAllAsync() {
            Lab7b.ServiceReference.GetAllRequest inValue = new Lab7b.ServiceReference.GetAllRequest();
            inValue.Body = new Lab7b.ServiceReference.GetAllRequestBody();
            return ((Lab7b.ServiceReference.WebServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.ServiceReference.GetDictResponse Lab7b.ServiceReference.WebServiceSoap.GetDict(Lab7b.ServiceReference.GetDictRequest request) {
            return base.Channel.GetDict(request);
        }
        
        public Lab7b.ServiceReference.Telephone[] GetDict() {
            Lab7b.ServiceReference.GetDictRequest inValue = new Lab7b.ServiceReference.GetDictRequest();
            inValue.Body = new Lab7b.ServiceReference.GetDictRequestBody();
            Lab7b.ServiceReference.GetDictResponse retVal = ((Lab7b.ServiceReference.WebServiceSoap)(this)).GetDict(inValue);
            return retVal.Body.GetDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.GetDictResponse> Lab7b.ServiceReference.WebServiceSoap.GetDictAsync(Lab7b.ServiceReference.GetDictRequest request) {
            return base.Channel.GetDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.ServiceReference.GetDictResponse> GetDictAsync() {
            Lab7b.ServiceReference.GetDictRequest inValue = new Lab7b.ServiceReference.GetDictRequest();
            inValue.Body = new Lab7b.ServiceReference.GetDictRequestBody();
            return ((Lab7b.ServiceReference.WebServiceSoap)(this)).GetDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.ServiceReference.AddDictResponse Lab7b.ServiceReference.WebServiceSoap.AddDict(Lab7b.ServiceReference.AddDictRequest request) {
            return base.Channel.AddDict(request);
        }
        
        public string AddDict(string surname, int number) {
            Lab7b.ServiceReference.AddDictRequest inValue = new Lab7b.ServiceReference.AddDictRequest();
            inValue.Body = new Lab7b.ServiceReference.AddDictRequestBody();
            inValue.Body.surname = surname;
            inValue.Body.number = number;
            Lab7b.ServiceReference.AddDictResponse retVal = ((Lab7b.ServiceReference.WebServiceSoap)(this)).AddDict(inValue);
            return retVal.Body.AddDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.AddDictResponse> Lab7b.ServiceReference.WebServiceSoap.AddDictAsync(Lab7b.ServiceReference.AddDictRequest request) {
            return base.Channel.AddDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.ServiceReference.AddDictResponse> AddDictAsync(string surname, int number) {
            Lab7b.ServiceReference.AddDictRequest inValue = new Lab7b.ServiceReference.AddDictRequest();
            inValue.Body = new Lab7b.ServiceReference.AddDictRequestBody();
            inValue.Body.surname = surname;
            inValue.Body.number = number;
            return ((Lab7b.ServiceReference.WebServiceSoap)(this)).AddDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.ServiceReference.UpdDictResponse Lab7b.ServiceReference.WebServiceSoap.UpdDict(Lab7b.ServiceReference.UpdDictRequest request) {
            return base.Channel.UpdDict(request);
        }
        
        public string UpdDict(int id, string surname, int number) {
            Lab7b.ServiceReference.UpdDictRequest inValue = new Lab7b.ServiceReference.UpdDictRequest();
            inValue.Body = new Lab7b.ServiceReference.UpdDictRequestBody();
            inValue.Body.id = id;
            inValue.Body.surname = surname;
            inValue.Body.number = number;
            Lab7b.ServiceReference.UpdDictResponse retVal = ((Lab7b.ServiceReference.WebServiceSoap)(this)).UpdDict(inValue);
            return retVal.Body.UpdDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.UpdDictResponse> Lab7b.ServiceReference.WebServiceSoap.UpdDictAsync(Lab7b.ServiceReference.UpdDictRequest request) {
            return base.Channel.UpdDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.ServiceReference.UpdDictResponse> UpdDictAsync(int id, string surname, int number) {
            Lab7b.ServiceReference.UpdDictRequest inValue = new Lab7b.ServiceReference.UpdDictRequest();
            inValue.Body = new Lab7b.ServiceReference.UpdDictRequestBody();
            inValue.Body.id = id;
            inValue.Body.surname = surname;
            inValue.Body.number = number;
            return ((Lab7b.ServiceReference.WebServiceSoap)(this)).UpdDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b.ServiceReference.DelDictResponse Lab7b.ServiceReference.WebServiceSoap.DelDict(Lab7b.ServiceReference.DelDictRequest request) {
            return base.Channel.DelDict(request);
        }
        
        public string DelDict(int id) {
            Lab7b.ServiceReference.DelDictRequest inValue = new Lab7b.ServiceReference.DelDictRequest();
            inValue.Body = new Lab7b.ServiceReference.DelDictRequestBody();
            inValue.Body.id = id;
            Lab7b.ServiceReference.DelDictResponse retVal = ((Lab7b.ServiceReference.WebServiceSoap)(this)).DelDict(inValue);
            return retVal.Body.DelDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b.ServiceReference.DelDictResponse> Lab7b.ServiceReference.WebServiceSoap.DelDictAsync(Lab7b.ServiceReference.DelDictRequest request) {
            return base.Channel.DelDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b.ServiceReference.DelDictResponse> DelDictAsync(int id) {
            Lab7b.ServiceReference.DelDictRequest inValue = new Lab7b.ServiceReference.DelDictRequest();
            inValue.Body = new Lab7b.ServiceReference.DelDictRequestBody();
            inValue.Body.id = id;
            return ((Lab7b.ServiceReference.WebServiceSoap)(this)).DelDictAsync(inValue);
        }
    }
}
